[{
    "company_name":"hcl",
    "date":ISODate("2024-09-25"),
    "students_appeared":"Ajay,jenifer,jeo,leron,angel,rezana"
},
{
    "company_name":"cts",
    "date":ISODate("2024-10-16"),
    "students_appeared":"kingsly,sanjay,ebin,john,shakthi"
},
{
    "company_name":"tcs",
    "date":ISODate("2024-10-27"),
    "students_appeared":"Santiago,cruz,deni,sri,abi"
},
{
    "company_name":"zoho",
    "date":ISODate("2024-11-15"),
    "students_appeared":"naveen,suman,felix,jethri,ashwin"
},
{
    "company_name":"guvi",
    "date":ISODate("2024-11-25"),
    "students_appeared":"jeshvi,jackson,rohit,yoga,edwinraj"
}]